commands:
  - name: clean-release-conflict
    help: "Delete helm release version secret to fix helm upgrade conflict"
  - name: ctx
    help: "Set kubectl context"
  - name: debug
    help: "bash into a pod through debug container"
    arguments:
      - name: image
        help: "image to use for debug container"
        short: i
        default: "tokyo2006/dev-tools:latest"
        required: False
  - name: copy
    help: "Copy files from pod"
    arguments:
      - name: local
        help: "local path to copy to"
        short: l
        required: True
      - name: remote
        help: "remote path to copy from"
        short: r
        required: True
  - name: exec
    help: "bash into a pod's container"
  - name: secret
    help: "Get secret values from a secret"
  
